import type { MonthlyReportMaterialCategoryDetailItem } from "./monthly-report-item-mapper.service";
import type {
  MonthlyReportMaterialCategoryAmountTotals,
  MonthlyReportMaterialCategorySummaryItem,
  MonthlyReportMaterialCategorySummaryTotals,
  MonthlyReportMaterialSummaryItem,
} from "./monthly-report-material-category.service";
import type { MonthlyReportMaterialCategoryWorkshopSummaryItem } from "./monthly-report-material-category-workshop.helper";
import type {
  MonthlyReportExcelRow,
  MonthlyReportExcelSheet,
} from "./monthly-reporting.formatters";

function buildTotalRow(values: Array<string | number>): MonthlyReportExcelRow {
  return {
    values,
    styleId: "Total",
  };
}

function buildCategorySummaryTotalRow(
  totals: MonthlyReportMaterialCategoryAmountTotals,
): MonthlyReportExcelRow {
  return buildTotalRow([
    "总计",
    "",
    totals.openingCostAmount,
    totals.inboundAmount,
    totals.outboundAmount,
    totals.closingCostAmount,
    totals.acceptanceInboundAmount,
    totals.supplierReturnAmount,
    totals.purchaseNetInboundAmount,
    totals.productionReceiptAmount,
    totals.netSalesAmount,
    totals.netSalesCostAmount,
    totals.workshopNetConsumptionCostAmount,
    totals.inventoryCostNetChangeAmount,
  ]);
}

export function buildMaterialCategoryExportSheets(params: {
  yearMonth: string;
  totals: Omit<MonthlyReportMaterialCategorySummaryTotals, "categoryCount">;
  categoryItems: MonthlyReportMaterialCategorySummaryItem[];
  materialItems: MonthlyReportMaterialSummaryItem[];
  workshopItems: MonthlyReportMaterialCategoryWorkshopSummaryItem[];
  detailItems: MonthlyReportMaterialCategoryDetailItem[];
}): MonthlyReportExcelSheet[] {
  const reportTitle = `${params.yearMonth} 物料分类月报`;

  return [
    {
      name: "总览",
      title: `${reportTitle} - 总览`,
      columnWidths: [160, 100],
      columns: ["指标", "值"],
      rows: [
        ["月初金额", params.totals.openingCostAmount],
        ["入库金额", params.totals.inboundAmount],
        ["出库金额", params.totals.outboundAmount],
        ["月末金额", params.totals.closingCostAmount],
        ["验收入库计价金额", params.totals.acceptanceInboundAmount],
        ["生产入库计价金额", params.totals.productionReceiptAmount],
        ["退厂计价金额", params.totals.supplierReturnAmount],
        ["采购净入库金额", params.totals.purchaseNetInboundAmount],
        ["车间领料成本", params.totals.workshopPickCostAmount],
        ["车间退料冲回成本", params.totals.workshopReturnCostAmount],
        ["车间报废成本", params.totals.workshopScrapCostAmount],
        ["车间净耗用成本", params.totals.workshopNetConsumptionCostAmount],
        ["销售出库销售价金额", params.totals.salesOutboundSalesAmount],
        ["销售出库成本", params.totals.salesOutboundCostAmount],
        ["销售退货销售价金额", params.totals.salesReturnSalesAmount],
        ["销售退货成本", params.totals.salesReturnCostAmount],
        ["销售净额（WMS 销售价口径）", params.totals.netSalesAmount],
        ["销售净成本", params.totals.netSalesCostAmount],
        ["WMS 商品毛利估算", params.totals.estimatedGrossProfitAmount],
        ["金额变动", params.totals.inventoryCostNetChangeAmount],
        ["单据行数", params.totals.lineCount],
        ["业务单据数", params.totals.documentCount],
      ] as Array<Array<string | number>>,
    },
    {
      name: "分类汇总",
      title: `${reportTitle} - 分类汇总`,
      columns: [
        "分类编码",
        "分类名称",
        "月初金额",
        "入库金额",
        "出库金额",
        "月末金额",
        "验收入库计价金额",
        "退厂计价金额",
        "采购净入库金额",
        "生产入库计价金额",
        "销售净额（WMS 销售价口径）",
        "销售净成本",
        "车间净耗用成本",
        "金额变动",
      ],
      rows: [
        ...params.categoryItems.map((item) => [
          item.categoryCode ?? "",
          item.categoryName,
          item.openingCostAmount,
          item.inboundAmount,
          item.outboundAmount,
          item.closingCostAmount,
          item.acceptanceInboundAmount,
          item.supplierReturnAmount,
          item.purchaseNetInboundAmount,
          item.productionReceiptAmount,
          item.netSalesAmount,
          item.netSalesCostAmount,
          item.workshopNetConsumptionCostAmount,
          item.inventoryCostNetChangeAmount,
        ]),
        buildCategorySummaryTotalRow(params.totals),
      ],
    },
    {
      name: "物料汇总",
      title: `${reportTitle} - 物料汇总`,
      columns: [
        "分类编码",
        "分类名称",
        "物料编码",
        "物料名称",
        "规格型号",
        "单位",
        "单据行数",
        "业务单据数",
        "月初数量",
        "月初金额",
        "入库金额",
        "出库金额",
        "库存净变动数量",
        "金额变动",
        "月末数量",
        "月末金额",
        "库存流入数量",
        "库存流出数量",
        "验收入库数量",
        "验收入库计价金额",
        "生产入库数量",
        "生产入库计价金额",
        "退给厂家数量",
        "退厂计价金额",
        "采购净入库金额",
        "车间领料数量",
        "车间领料成本",
        "车间退料数量",
        "车间退料冲回成本",
        "车间报废数量",
        "车间报废成本",
        "车间净耗用数量",
        "车间净耗用成本",
        "销售出库数量",
        "销售出库销售价金额",
        "销售出库成本",
        "销售退货数量",
        "销售退货销售价金额",
        "销售退货成本",
        "净销售数量",
        "销售净额（WMS 销售价口径）",
        "销售净成本",
        "WMS 商品毛利估算",
      ],
      rows: params.materialItems.map((item) => [
        item.categoryCode ?? "",
        item.categoryName,
        item.materialCode,
        item.materialName,
        item.materialSpec ?? "",
        item.unitCode,
        item.lineCount,
        item.documentCount,
        item.openingQuantity,
        item.openingCostAmount,
        item.inboundAmount,
        item.outboundAmount,
        item.inventoryNetChangeQuantity,
        item.inventoryCostNetChangeAmount,
        item.closingQuantity,
        item.closingCostAmount,
        item.inQuantity,
        item.outQuantity,
        item.acceptanceInboundQuantity,
        item.acceptanceInboundAmount,
        item.productionReceiptQuantity,
        item.productionReceiptAmount,
        item.supplierReturnQuantity,
        item.supplierReturnAmount,
        item.purchaseNetInboundAmount,
        item.workshopPickQuantity,
        item.workshopPickCostAmount,
        item.workshopReturnQuantity,
        item.workshopReturnCostAmount,
        item.workshopScrapQuantity,
        item.workshopScrapCostAmount,
        item.workshopNetConsumptionQuantity,
        item.workshopNetConsumptionCostAmount,
        item.salesOutboundQuantity,
        item.salesOutboundSalesAmount,
        item.salesOutboundCostAmount,
        item.salesReturnQuantity,
        item.salesReturnSalesAmount,
        item.salesReturnCostAmount,
        item.netSalesQuantity,
        item.netSalesAmount,
        item.netSalesCostAmount,
        item.estimatedGrossProfitAmount,
      ]) as Array<Array<string | number>>,
    },
    {
      name: "车间使用汇总",
      title: `${reportTitle} - 车间使用汇总`,
      columns: [
        "车间",
        "单据行数",
        "业务单据数",
        "领料成本",
        "退料冲回成本",
        "报废成本",
        "车间净耗用成本",
      ],
      rows: params.workshopItems.map((item) => [
        item.workshopName,
        item.lineCount,
        item.documentCount,
        item.pickCostAmount,
        item.returnCostAmount,
        item.scrapCostAmount,
        item.netConsumptionCostAmount,
      ]) as Array<Array<string | number>>,
    },
    {
      name: "单据行明细",
      title: `${reportTitle} - 单据行明细`,
      columns: [
        "分类编码",
        "分类名称",
        "单据类型",
        "单据编号",
        "行号",
        "业务日期",
        "仓别",
        "车间",
        "物料编码",
        "物料名称",
        "规格型号",
        "单位",
        "销售项目编码",
        "销售项目名称",
        "数量",
        "成本单价",
        "成本金额",
        "销售价",
        "销售金额",
        "来源月份",
        "来源单据",
      ],
      rows: params.detailItems.map((item) => [
        item.categoryCode ?? "",
        item.categoryName,
        item.documentTypeLabel,
        item.documentNo,
        item.lineNo,
        item.bizDate,
        item.stockScopeName ?? "",
        item.workshopName ?? "",
        item.materialCode,
        item.materialName,
        item.materialSpec ?? "",
        item.unitCode,
        item.salesProjectCode ?? "",
        item.salesProjectName ?? "",
        item.quantity,
        item.unitPrice,
        item.amount,
        item.salesUnitPrice ?? "",
        item.salesAmount ?? "",
        item.sourceBizMonth ?? "",
        item.sourceDocumentNo ?? "",
      ]) as Array<Array<string | number>>,
    },
  ];
}
