<template>
  <div class="app-container demand-page">
    <el-card shadow="never">
      <template #header><div class="toolbar"><div><h2>研发采购需求汇总</h2><span class="muted">公共需求池按申请人排序，普通用户只能维护本人填报记录</span></div><el-button v-if="canCreate" type="primary" @click="openCreate">添加需求</el-button></div></template>
      <el-form :inline="true" class="filter-form" @submit.prevent><el-form-item label="关键字"><el-input v-model="filters.keyword" clearable placeholder="申请人、项目、物料、供应商" @keyup.enter="search" /></el-form-item><el-form-item label="需求日期"><el-date-picker v-model="filters.needDate" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" /></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form>
      <el-table v-loading="loading" :data="rows" stripe border>
        <el-table-column prop="applicantName" label="申请人" min-width="100" fixed /><el-table-column prop="departmentName" label="所属部门" min-width="110" /><el-table-column label="需求日期" width="120"><template #default="{ row }">{{ dateOnly(row.needDate) }}</template></el-table-column>
        <el-table-column label="所属项目" min-width="190"><template #default="{ row }"><div>{{ row.projectNameSnapshot }}</div><small>{{ row.projectCodeSnapshot }}</small></template></el-table-column><el-table-column prop="materialName" label="物料名称" min-width="150" /><el-table-column prop="specification" label="规格/型号" min-width="180" show-overflow-tooltip /><el-table-column prop="unit" label="单位" width="70" /><el-table-column prop="quantity" label="数量" width="130" class-name="numeric-column" /><el-table-column prop="supplierText" label="供应商" min-width="160" show-overflow-tooltip /><el-table-column label="采购链接" width="100"><template #default="{ row }"><el-link v-if="row.purchaseUrl" :href="row.purchaseUrl" target="_blank" type="primary">打开链接</el-link><span v-else>—</span></template></el-table-column>
        <el-table-column label="备注/图片" min-width="180" show-overflow-tooltip><template #default="{ row }"><span>{{ row.noteText || "—" }}</span><el-tag v-if="imageCount(row)" size="small" class="image-tag">{{ imageCount(row) }}图</el-tag></template></el-table-column><el-table-column label="最后修改" min-width="150"><template #default="{ row }"><div>{{ row.updatedBy || row.createdBy || "—" }}</div><small>{{ formatDateTime(row.updatedAt || row.createdAt) }}</small></template></el-table-column><el-table-column label="操作" fixed="right" width="150"><template #default="{ row }"><el-button v-if="canEdit(row)" link type="primary" @click="openEdit(row)">编辑</el-button><el-button v-if="canEdit(row)" link type="danger" @click="removeRow(row)">删除</el-button><span v-if="!canEdit(row)" class="muted">查看</span></template></el-table-column>
      </el-table><pagination v-show="total > 0" v-model:page="page.pageNum" v-model:limit="page.pageSize" :total="total" @pagination="load" />
    </el-card>
    <el-drawer v-model="drawer.open" :title="drawer.editing ? '编辑研发采购需求' : '批量添加研发采购需求'" size="760px" destroy-on-close>
      <el-form :model="drawer.form" label-width="90px"><el-form-item label="需求日期" required><el-date-picker v-model="drawer.form.needDate" type="date" value-format="YYYY-MM-DD" /></el-form-item><div v-for="(line, index) in drawer.form.lines" :key="line._key" class="demand-line"><div class="line-title">物料明细 {{ index + 1 }}<el-button v-if="!drawer.editing && drawer.form.lines.length > 1" link type="danger" @click="drawer.form.lines.splice(index, 1)">移除</el-button></div><el-form-item label="研发项目" required><el-select v-model="line.rdProjectId" filterable clearable placeholder="选择有效研发项目" @focus="loadProjects"><el-option v-for="project in projects" :key="project.id" :label="`${project.projectCode} ${project.projectName}`" :value="project.id" /></el-select></el-form-item><el-row :gutter="12"><el-col :span="12"><el-form-item label="物料名称" required><el-input v-model="line.materialName" /></el-form-item></el-col><el-col :span="12"><el-form-item label="规格/型号" required><el-input v-model="line.specification" /></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :span="8"><el-form-item label="单位" required><el-input v-model="line.unit" /></el-form-item></el-col><el-col :span="8"><el-form-item label="数量" required><el-input-number v-model="line.quantity" :min="0.000001" :precision="6" controls-position="right" style="width: 100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="供应商"><el-input v-model="line.supplierText" /></el-form-item></el-col></el-row><el-form-item label="采购链接"><el-input v-model="line.purchaseUrl" placeholder="https://..." /></el-form-item><el-form-item label="备注"><el-input v-model="line.noteText" type="textarea" :rows="2" /></el-form-item><el-form-item label="图片"><el-upload action="/api/files/upload" :headers="uploadHeaders" :limit="6" list-type="picture-card" :on-success="(response) => onUpload(response, line)" :on-remove="(_, fileList) => onRemoveUpload(fileList, line)"><el-icon><Plus /></el-icon></el-upload></el-form-item></div><el-button v-if="!drawer.editing" plain @click="addLine">添加一行</el-button></el-form>
      <template #footer><el-button @click="drawer.open = false">取消</el-button><el-button type="primary" :loading="drawer.saving" @click="save">确认保存</el-button></template>
    </el-drawer>
  </div>
</template>
<script setup>
import { computed, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { Plus } from "@element-plus/icons-vue";
import { createRdProcurementDemands, deleteRdProcurementDemand, listRdProcurementDemands, listRdProjects, updateRdProcurementDemand } from "@/api/rd-subwarehouse";
import useUserStore from "@/store/modules/user";
import { checkPermi } from "@/utils/permission";
import { getToken } from "@/utils/auth";
const userStore = useUserStore(); const rows = ref([]); const projects = ref([]); const loading = ref(false); const total = ref(0); const page = reactive({ pageNum: 1, pageSize: 20 }); const filters = reactive({ keyword: "", needDate: [] }); const drawer = reactive({ open: false, editing: false, saving: false, demandId: null, form: { needDate: "", lines: [] } }); const uploadHeaders = computed(() => ({ Authorization: `Bearer ${getToken()}` })); const canCreate = computed(() => checkPermi(["rd:procurement-demand:create"]));
function newLine() { return { _key: `${Date.now()}-${Math.random()}`, rdProjectId: undefined, materialName: "", specification: "", unit: "", quantity: 1, supplierText: "", purchaseUrl: "", noteText: "", imageMetadata: [] }; } function addLine() { drawer.form.lines.push(newLine()); } function openCreate() { drawer.editing = false; drawer.demandId = null; drawer.form.needDate = new Date().toISOString().slice(0, 10); drawer.form.lines = [newLine()]; drawer.open = true; loadProjects(); } function openEdit(row) { drawer.editing = true; drawer.demandId = row.id; drawer.form.needDate = dateOnly(row.needDate); drawer.form.lines = [{ ...row, _key: row.id, imageMetadata: Array.isArray(row.imageMetadata) ? row.imageMetadata : [] }]; drawer.open = true; loadProjects(); }
async function loadProjects() { if (projects.value.length) return; try { const response = await listRdProjects({ limit: 100, offset: 0 }); projects.value = response.data?.items || []; } catch { /* interceptor handles */ } } async function load() { loading.value = true; try { const response = await listRdProcurementDemands({ keyword: filters.keyword || undefined, needDateFrom: filters.needDate?.[0], needDateTo: filters.needDate?.[1], limit: page.pageSize, offset: (page.pageNum - 1) * page.pageSize }); rows.value = response.data?.items || []; total.value = response.data?.total || 0; } finally { loading.value = false; } } function search() { page.pageNum = 1; load(); } function reset() { filters.keyword = ""; filters.needDate = []; search(); } function canEdit(row) { return row.applicantUserId === userStore.id || checkPermi(["rd:procurement-demand:manage"]); } function onUpload(response, line) { const result = response?.data || response; if (result?.url) line.imageMetadata.push({ url: result.url, name: result.originalName || result.fileName, size: result.size }); } function onRemoveUpload(fileList, line) { line.imageMetadata = fileList.map((file) => file.response?.data || file.response).filter((item) => item?.url).map((item) => ({ url: item.url, name: item.originalName || item.fileName, size: item.size })); } function imageCount(row) { return Array.isArray(row.imageMetadata) ? row.imageMetadata.length : 0; } function dateOnly(value) { return value ? String(value).slice(0, 10) : ""; } function formatDateTime(value) { return value ? new Date(value).toLocaleString("zh-CN", { hour12: false }) : ""; }
async function save() { const line = drawer.form.lines[0]; if (!drawer.form.needDate || !line?.rdProjectId || !line.materialName || !line.specification || !line.unit || !(line.quantity > 0)) { ElMessage.warning("请完整填写需求日期和物料必填项"); return; } drawer.saving = true; try { if (drawer.editing) { await updateRdProcurementDemand(drawer.demandId, { rdProjectId: line.rdProjectId, materialName: line.materialName, specification: line.specification, unit: line.unit, quantity: line.quantity, supplierText: line.supplierText || undefined, purchaseUrl: line.purchaseUrl || undefined, noteText: line.noteText || undefined, imageMetadata: line.imageMetadata }); ElMessage.success("保存成功"); } else { await createRdProcurementDemands({ needDate: drawer.form.needDate, clientRequestId: crypto.randomUUID(), lines: drawer.form.lines.map(({ _key, ...item }) => item) }); ElMessage.success("需求已加入公共汇总表"); } drawer.open = false; await load(); } finally { drawer.saving = false; } } async function removeRow(row) { await ElMessageBox.confirm("删除后该需求将从公共汇总表隐藏，是否继续？", "提示", { type: "warning" }); await deleteRdProcurementDemand(row.id); ElMessage.success("已删除"); await load(); } load();
</script>
<style scoped>
.toolbar { display: flex; align-items: center; justify-content: space-between; gap: 16px; }.toolbar h2 { margin: 0 0 6px; font-size: 20px; }.muted { color: var(--el-text-color-secondary); font-size: 12px; }.filter-form { margin-bottom: 16px; }.demand-line { margin: 12px 0 20px; padding: 14px; border: 1px solid var(--el-border-color-lighter); border-radius: 6px; }.line-title { display: flex; justify-content: space-between; margin-bottom: 12px; }.image-tag { margin-left: 6px; } small { color: var(--el-text-color-secondary); }
</style>
